Create models
Hoodrich42/dj_ln pull request #1
Opened 2024-04-16 11:54 UTC by Hoodrich42

2024-04-16 14:45 UTC, arrrsik commented on greenai/greenai/settings.py
> +SECRET_KEY = 'django-insecure-zr0affoy7id$r77q#7mf7e!a&itwe5r9-slb*d-hrveae+b0wt'
Секретный ключ???😯😯😯

2024-04-16 14:48 UTC, arrrsik commented on greenai/store/models.py
> +    phone_number = models.PositiveBigIntegerField()
PositiveSmallIntegerField?

2024-04-16 14:52 UTC, arrrsik commented on greenai/store/models.py
> +                   ('m', 'M'),
Вторая S,M... и т.д лишние же лучше писать полностью слово

2024-04-16 14:53 UTC, arrrsik commented on greenai/store/models.py
> +    surname = models.CharField(max_length=255, blank=True, null=True)
в CharField не стоит использовать null=True.

2024-04-16 14:54 UTC, arrrsik commented on greenai/store/models.py
> +    first_name = models.CharField(max_length=255)
verbose_name?

2024-04-16 14:57 UTC, arrrsik commented on greenai/store/models.py
> +    category = models.ForeignKey('Category', on_delete=models.PROTECT)
Почему решил использовать PROTECT?

2024-04-16 15:00 UTC, arrrsik commented on greenai/store/models.py
> +    date_and_time_of_creation = models.DateField(auto_now_add=True)
Название поле топ))), но нужно короче например dc(date_create)

2024-04-16 15:01 UTC, arrrsik commented on greenai/store/models.py
> +    user_id = models.ForeignKey('Users', on_delete=models.PROTECT)
Почему PROTECT

2024-04-16 15:04 UTC, arrrsik commented on greenai/store/models.py
> +
Class Meta?

2024-04-16 15:08 UTC, arrrsik commented on greenai/store/models.py
> +    user_id = models.ForeignKey('Users', on_delete=models.PROTECT)
Не хочется связь O2O(One to One) сделать?

2024-04-16 15:09 UTC, arrrsik commented on greenai/store/models.py
> +    items = models.ManyToManyField('Items', blank=True, related_name='items')
blank=True?

2024-04-16 15:14 UTC, arrrsik commented on greenai/store/models.py
> +    description = models.TextField()
Хочешь помучать пользователей, просто оценку нельзя поставить?)

2024-04-16 15:16 UTC, arrrsik commented on greenai/store/models.py
> +    def get_sum(self):
Можно метод покрыть декоратором @property

2024-04-16 15:22 UTC, arrrsik commented on greenai/store/models.py
> +class Items(models.Model):
Модели пишутся в ед. числе

2024-04-16 15:26 UTC, arrrsik commented on greenai/store/models.py
> +            sum += Items.objects.get(name=item).price
Если объектов Items с одинаковым полем name будет много, то вернет ошибку т.к метод get возвращает только один объект из БД.

2024-04-16 15:27 UTC, arrrsik commented on greenai/store/models.py
> +    role_choise = [('saler', 'Продавец'),
Где-то по русски где-то по английски

2024-04-16 15:28 UTC, arrrsik requested changes

2024-04-16 15:28 UTC, arrrsik commented on greenai/store/models.py
> +    phone_number = models.PositiveBigIntegerField()
verbose_name?

2024-04-17 13:06 UTC, Hoodrich42 commented on greenai/greenai/settings.py
> +SECRET_KEY = 'django-insecure-zr0affoy7id$r77q#7mf7e!a&itwe5r9-slb*d-hrveae+b0wt'
✅

2024-04-17 13:22 UTC, Hoodrich42 commented on greenai/store/models.py
> +class Items(models.Model):
✅

2024-04-17 13:22 UTC, Hoodrich42 commented on greenai/store/models.py
> +    surname = models.CharField(max_length=255, blank=True, null=True)
✅

2024-04-17 13:22 UTC, Hoodrich42 commented on greenai/store/models.py
> +    first_name = models.CharField(max_length=255)
✅

2024-04-17 13:22 UTC, Hoodrich42 commented on greenai/store/models.py
> +    date_and_time_of_creation = models.DateField(auto_now_add=True)
✅

2024-04-17 13:23 UTC, Hoodrich42 commented on greenai/store/models.py
> +    items = models.ManyToManyField('Items', blank=True, related_name='items')
Корзина же может быть пустой

2024-04-17 13:24 UTC, Hoodrich42 commented on greenai/store/models.py
> +            sum += Items.objects.get(name=item).price
✅ Заменил get на filter

2024-04-17 13:25 UTC, Hoodrich42 commented on greenai/store/models.py
> +    phone_number = models.PositiveBigIntegerField()
✅

2024-04-17 13:28 UTC, Hoodrich42 commented on greenai/store/models.py
> +
✅

2024-04-17 13:45 UTC, Hoodrich42 commented on greenai/store/models.py
> +                   ('m', 'M'),
Тут же первое значение заносится в бд, второе значение видит пользователь. Одно оставить нельзя, когда пытался сделать миграцию с одним, он требует кортеж

2024-04-17 13:49 UTC, Hoodrich42 commented on greenai/store/models.py
> +    category = models.ForeignKey('Category', on_delete=models.PROTECT)
В модели Товар поле category on_delete=models.PROTECT потому что пока есть хоть один товар такой категории, категорию нельзя удалять.

В модели Корзина поле user сделал onetoonefield и on_delete=models.CASCADE, чтобы если удалить пользователя корзина его тоже удалилась

В модели Обзоры поле user on_delete=models.SET_NULL, чтобы отзыв остался и просто был без автора, если вдруг удалить пользователя

2024-04-17 13:49 UTC, Hoodrich42 commented on greenai/store/models.py
> +    category = models.ForeignKey('Category', on_delete=models.PROTECT)
Отпиши если я правильно понимаю все это, может я не так осознал для чего нужен on_delete

2024-04-17 13:49 UTC, Hoodrich42 commented on greenai/store/models.py
> +    user_id = models.ForeignKey('Users', on_delete=models.PROTECT)
✅

2024-04-17 13:50 UTC, Hoodrich42 commented on greenai/store/models.py
> +    def get_sum(self):
✅

2024-04-18 18:49 UTC, merged